#!/bin/env bash

# Get current workspace name
workspace_name=$(
i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).name' \
  | cut -d"\"" -f2
)

# Get current screen name
screen=$(
i3-msg -t get_workspaces \
  | jq '.[] | select(.focused==true).output' \
  | cut -d"\"" -f2
)

# Get current layout
layout=$(
i3-msg -t get_tree \
  | jq ".nodes | .[] \
  | select(.name==\"${screen}\").nodes | .[] \
  | select(.name==\"content\").nodes | .[] \
  | select(.name==\"${workspace_name}\").nodes \
  | .[0].layout" \
  | cut -d"\"" -f2
)

case $layout in 
  "splith" | "splitv")
    color="green"
    ;;
  "stacked")
    color="orange"
    ;;
  "tabbed")
    color="yellow"
    ;;
  *)
    color="FF0000"
    ;;
esac

echo "<span color='${color}'>${layout}</span>"
